### ISSUE TITLE
'orig' is not a valid size in Attachment::calculateUrl

### ISSUE THREAD

**Issue by sb-relaxt-at** [justimmo/php-sdk#144]
It is not possible to explicitly get the original URL, which is a breaking change, see https://github.com/justimmo/php-sdk/blob/e690b34594281b4b0c071ec7ba1462433f5c4b00/src/Justimmo/Model/Attachment.php#L82

From my understanding it should be possible to get the original url as this is still the default parameter value.

**Comment by simitter** [comment]
thx we will look into it.
