### ISSUE TITLE
Prices

### ISSUE THREAD

**Issue by daves-weblab** [justimmo/php-sdk#38]
I have the prices set in Justimmo to be public, but some fields in the Realty Object are empty:

contractEstablishmentCosts
transferTax
landRegistration
contactEstablishmentCosts

Justimmo Setup:
![justimmo](https://cloud.githubusercontent.com/assets/14099785/10652732/4be24650-7859-11e5-8d15-f55e6ebbbd80.png)

Empty Fields:
![emtpy fields](https://cloud.githubusercontent.com/assets/14099785/10652757/6f2763ac-7859-11e5-867b-0b02b1fad4e1.png)

**Comment by Tschebel** [comment]
Are u using the list or detail call for the realty?
```php
$query->find(); //list call
$query->findPk(); //detail call
```
In the list call not every information is sent by the api, thus leaving some fields empty

**Comment by daves-weblab** [comment]
Hi,

I am using the $query->findPk() method to fetch information about a single listing.

 

Best regards

David

**Comment by daves-weblab** [comment]
with the newest SDK I tried a simple example without the overhead of the whole application

![example](https://cloud.githubusercontent.com/assets/14099785/10943651/8594a8ea-8315-11e5-91d3-55b6f25c5fbf.jpg)

but the incidental costs are still empty. Is there anything I have to look out for now in the Justimmo Backend when setting the costs because it worked fine some time ago.
