### ISSUE TITLE
Changed mapping of personennummer/id breaks contact person of Projects and Realties partially

### ISSUE THREAD

**Issue by sb-relaxt-at** [justimmo/php-sdk#62]
The mapping of the personennummer (which originally had been mapped to the id) [has been changed](https://github.com/justimmo/php-sdk/commit/70afc63356aa5adbbc4e686bf485bf2378001575) in order to compensate for a breaking API change. As a side-effect Employees retrieved as contact persons of a Project or Realty have no longer an id set. When querying a Realty or a Project, the resulting xml does not contain an element "id" in the element "kontaktperson", there is only the "personennummer" set to the id, which in turn, no longer maps to the id.

**Comment by 19Gerhard85** [comment]
@sb-relaxt-at 
Danke für den Hinweis. Die fehlende ID wurde ergänzt.

**Comment by sb-relaxt-at** [comment]
Danke für die rasche Reaktion, es ist aber nur teilweise behoben, bei der Kontaktperson eines Projektes fehlt das id Element weiterhin.

**Comment by 19Gerhard85** [comment]
@sb-relaxt-at 
Die fehlende ID ist nun auch beim Projekt vorhanden.

**Comment by sb-relaxt-at** [comment]
Vielen Dank!
