### ISSUE TITLE
Curl Timeout Exposé Download

### ISSUE THREAD

**Issue by 19Gerhard85** [justimmo/php-sdk#64]

**Comment by 19Gerhard85** [comment]
@Tschebel 
Der Curl Request timed bei größeren Exposés aus.

Eventuell mit `$request->setOption(CURLOPT_TIMEOUT, 1800);` erhöhen?

**Comment by Tschebel** [comment]
Curl Optionen koennen auch von aussen angepasst werden ueber die JustimmoAPI:
```php
$api->setCurlOption(CURLOPT_TIMEOUT, 1800);
```

**Comment by 19Gerhard85** [comment]
@Tschebel 
Alles klar. Dann sollten wir das vielleicht für die Exposé Funktion setzen.
